# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10o3FLlDLn7kmpjBAojEyGyt5t6zRX-Ln
"""

pip install streamlit

import streamlit as st
import pickle
import numpy as np

# Load model
model = pickle.load(open('model.pkl', 'rb'))

st.title('Prediksi Kepuasan Pelanggan')

# Input dari pengguna
age = st.number_input('Umur', min_value=0, max_value=100, step=1)
gender = st.selectbox('Jenis Kelamin', ('Pria', 'Wanita'))
income = st.number_input('Pendapatan Tahunan', min_value=0)
score = st.number_input('Skor Pengeluaran', min_value=0, max_value=100, step=1)

# Konversi input ke dalam bentuk yang sesuai untuk model
gender_encoded = 1 if gender == 'Pria' else 0
features = np.array([[age, gender_encoded, income, score]])

if st.button('Prediksi'):
    prediction = model.predict(features)
    output = 'Puas' if prediction[0] == 1 else 'Tidak Puas'
    st.write(f'Prediksi Kepuasan Pelanggan: {output}')